<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
 * Kenya Counties and Sub-Counties
 * Used for agent region detection and manual fallback selection.
 */

$kenya_regions = [
    'Baringo' => ['Baringo Central','Baringo North','Baringo South','Eldama Ravine','Mogotio','Tiaty'],
    'Bomet' => ['Bomet Central','Bomet East','Chepalungu','Konoin','Sotik'],
    'Bungoma' => ['Bumula','Kabuchai','Kanduyi','Kimilili','Mt Elgon','Sirisia','Tongaren','Webuye East','Webuye West'],
    'Busia' => ['Budalangi','Butula','Funyula','Nambale','Teso North','Teso South'],
    'Elgeyo-Marakwet' => ['Keiyo North','Keiyo South','Marakwet East','Marakwet West'],
    'Embu' => ['Embu East','Embu North','Embu West','Manyatta','Mbeere North','Mbeere South','Runyenjes'],
    'Garissa' => ['Balambala','Dadaab','Fafi','Garissa Township','Hulugho','Ijara','Lagdera'],
    'Homa Bay' => ['Gem','Homa Bay Town','Kabondo Kasipul','Karachuonyo','Kasipul','Mbita','Ndhiwa','Rangwe','Suba North','Suba South'],
    'Isiolo' => ['Garba Tulla','Isiolo','Merti'],
    'Kajiado' => ['Kajiado Central','Kajiado East','Kajiado North','Kajiado South','Loitokitok','Mashuuru'],
    'Kakamega' => ['Butere','Ikolomani','Khwisero','Likuyani','Lugari','Lurambi','Malava','Matungu','Mumias East','Mumias West','Navakholo','Shinyalu'],
    'Kericho' => ['Ainamoi','Belgut','Bureti','Kipkelion East','Kipkelion West','Soin Sigowet'],
    'Kiambu' => ['Gatundu North','Gatundu South','Githunguri','Juja','Kabete','Kiambaa','Kiambu','Kikuyu','Kinoo','Lari','Limuru','Ruiru','Thika Town','Wp Gatanga'],
    'Kilifi' => ['Bahari','Ganze','Kaloleni','Kilifi North','Kilifi South','Magarini','Malindi','Rabai'],
    'Kirinyaga' => ['Gichugu','Kirinyaga Central','Mwea East','Mwea West','Ndia'],
    'Kisii' => ['Bobasi','Bomachoge Borabu','Bomachoge Chache','Bonchari','Kitutu Chache North','Kitutu Chache South','Nyaribari Chache','Nyaribari Masaba','South Mugirango'],
    'Kisumu' => ['Kisumu Central','Kisumu East','Kisumu West','Kolwa East','Kolwa West','Muhoroni','Nyakach','Nyando','Seme'],
    'Kitui' => ['Ikutha','Katulani','Kibwezi East','Kitui Central','Kitui East','Kitui Rural','Kitui South','Kitui West','Lower Yatta','Matinyani','Mwingi Central','Mwingi North','Mwingi West','Mutonguni','Nzambani','Tseikuru'],
    'Kwale' => ['Kinango','Lungalunga','Matuga','Msambweni'],
    'Laikipia' => ['Laikipia Central','Laikipia East','Laikipia North','Laikipia West','Mukogodo East','Mukogodo West'],
    'Lamu' => ['Lamu East','Lamu West'],
    'Machakos' => ['Kathiani','Machakos Town','Masinga','Matungulu','Mavoko','Mwala','Yatta'],
    'Makueni' => ['Kaiti','Kibwezi West','Kilome','Makueni','Mbooni','Nzaui'],
    'Mandera' => ['Banissa','Lafey','Mandera East','Mandera North','Mandera South','Mandera West'],
    'Marsabit' => ['Laisamis','Moyale','North Imenti','Saku'],
    'Meru' => ['Buuri','Igembe Central','Igembe North','Igembe South','Imenti North','Imenti South','Tigania East','Tigania West'],
    'Migori' => ['Awendo','Kuria East','Kuria West','Mabera','Ntimaru','Rongo','Suna East','Suna West','Uriri'],
    'Mombasa' => ['Changamwe','Jomvu','Kisauni','Likoni','Mvita','Nyali'],
    'Murang\'a' => ['Gatanga','Kahuro','Kandara','Kangema','Kigumo','Kiharu','Mathioya','Murang\'a South'],
    'Nairobi' => ['Dagoretti North','Dagoretti South','Embakasi Central','Embakasi East','Embakasi North','Embakasi South','Embakasi West','Kasarani','Kamukunji','Kibra','Lang\'ata','Makadara','Mathare','Roysambu','Ruaraka','Starehe','Westlands'],
    'Nakuru' => ['Bahati','Gilgil','Kuresoi North','Kuresoi South','Molo','Naivasha','Nakuru Town East','Nakuru Town West','Njoro','Rongai','Subukia'],
    'Nandi' => ['Aldai','Chesumei','Emgwen','Mosop','Nandi Hills','Tindiret'],
    'Narok' => ['Emurua Dikirr','Kilgoris','Narok East','Narok North','Narok South','Narok West'],
    'Nyamira' => ['Borabu','Kitutu Masaba','North Mugirango','West Mugirango'],
    'Nyandarua' => ['Kinangop','Kipipiri','Ndaragwa','Ol Kalou','Ol Jorok'],
    'Nyeri' => ['Kieni East','Kieni West','Mathira East','Mathira West','Mukurwe-ini','Nyeri Town','Othaya','Tetu'],
    'Samburu' => ['Samburu East','Samburu North','Samburu West'],
    'Siaya' => ['Alego Usonga','Bondo','Gem','Rarieda','Ugenya','Ugunja'],
    'Taita-Taveta' => ['Mwatate','Taveta','Voi','Wundanyi'],
    'Tana River' => ['Bura','Galole','Garsen'],
    'Tharaka-Nithi' => ['Chuka','Igambang\'ombe','Maara','Tharaka North','Tharaka South'],
    'Trans Nzoia' => ['Cherangany','Endebess','Kiminini','Kwanza','Saboti'],
    'Turkana' => ['Kibish','Loima','Turkana Central','Turkana East','Turkana North','Turkana South','Turkana West'],
    'Uasin Gishu' => ['Ainabkoi','Kapseret','Kesses','Moiben','Soy','Turbo'],
    'Vihiga' => ['Emuhaya','Hamisi','Luanda','Sabatia','Vihiga'],
    'Wajir' => ['Eldas','Tarbaj','Wajir East','Wajir North','Wajir South','Wajir West'],
    'West Pokot' => ['Central Pokot','North Pokot','Pokot South','West Pokot'],
];
